project_back_homepage:
    pattern:  /{_locale}
    defaults: { _controller: ProjectBackBundle:Default:index }
    requirements:
        _locale:  es|en

project_back_page_list:
    pattern:  /{_locale}/page/list/
    defaults: { _controller: ProjectBackBundle:Page:list }
    requirements:
        _locale:  es|en
project_back_page_rank:
    pattern:  /{_locale}/page/rank
    defaults: { _controller: ProjectBackBundle:Page:rank }
    requirements:
        _locale:  es|en
project_back_page_rank_post:
    pattern:  /{_locale}/page/rank/post
    defaults: { _controller: ProjectBackBundle:Page:rankPost }
    requirements:
        _locale:  es|en
project_back_page_create:
    pattern:  /{_locale}/page/create
    defaults: { _controller: ProjectBackBundle:Page:create }
    requirements:
        _locale:  es|en
project_back_page_edit:
    pattern:  /{_locale}/page/edit/{id}
    defaults: { _controller: ProjectBackBundle:Page:edit, id: '1' }
    requirements:
        _locale:  es|en
project_back_page_delete:
    pattern:  /{_locale}/page/delete
    defaults: { _controller: ProjectBackBundle:Page:delete }
    requirements:
      _method: POST
      _locale:  es|en
project_back_page_status:
    pattern:  /{_locale}/page/status
    defaults: { _controller: ProjectBackBundle:Page:status }
    requirements:
      _method: POST
      _locale:  es|en

project_back_background_list:
    pattern:  /{_locale}/background/list/
    defaults: { _controller: ProjectBackBundle:Background:list }
    requirements:
        _locale:  es|en
project_back_background_rank:
    pattern:  /{_locale}/background/rank
    defaults: { _controller: ProjectBackBundle:Background:rank }
    requirements:
        _locale:  es|en
project_back_background_rank_post:
    pattern:  /{_locale}/background/rank/post
    defaults: { _controller: ProjectBackBundle:Background:rankPost }
    requirements:
        _locale:  es|en
project_back_background_create:
    pattern:  /{_locale}/background/create
    defaults: { _controller: ProjectBackBundle:Background:create }
    requirements:
        _locale:  es|en
project_back_background_edit:
    pattern:  /{_locale}/background/edit/{id}
    defaults: { _controller: ProjectBackBundle:Background:edit, id: '1' }
    requirements:
        _locale:  es|en
project_back_background_delete:
    pattern:  /{_locale}/background/delete
    defaults: { _controller: ProjectBackBundle:Background:delete }
    requirements:
      _method: POST
      _locale:  es|en
project_back_background_status:
    pattern:  /{_locale}/background/status
    defaults: { _controller: ProjectBackBundle:Background:status }
    requirements:
      _method: POST
      _locale:  es|en