project_back_homepage:
    pattern:  /
    defaults: { _controller: ProjectBackBundle:Default:index }
project_back_delete:
    pattern:  /delete
    defaults: { _controller: ProjectBackBundle:Default:delete }
    requirements:
      _method: POST
    options:
        expose: true
project_back_status:
    pattern:  /status
    defaults: { _controller: ProjectBackBundle:Default:status }
    requirements:
      _method: POST
    options:
        expose: true
project_back_set_home:
    pattern:  /sethome
    defaults: { _controller: ProjectBackBundle:Default:setHome }
    requirements:
      _method: POST
    options:
        expose: true

project_back_page_list:
    pattern:  /page/list/
    defaults: { _controller: ProjectBackBundle:Page:list }
project_back_page_rank:
    pattern:  /page/rank
    defaults: { _controller: ProjectBackBundle:Page:rank }
project_back_page_rank_post:
    pattern:  /page/rank/post
    defaults: { _controller: ProjectBackBundle:Page:rankPost }
project_back_page_create:
    pattern:  /page/create
    defaults: { _controller: ProjectBackBundle:Page:create }
project_back_page_edit:
    pattern:  /page/edit/{id}
    defaults: { _controller: ProjectBackBundle:Page:edit, id: '1' }

project_back_category_list:
    pattern:  /category/list/
    defaults: { _controller: ProjectBackBundle:Category:list }
project_back_category_rank:
    pattern:  /category/rank
    defaults: { _controller: ProjectBackBundle:Category:rank }
project_back_category_rank_post:
    pattern:  /category/rank/post
    defaults: { _controller: ProjectBackBundle:Category:rankPost }
project_back_category_create:
    pattern:  /category/create
    defaults: { _controller: ProjectBackBundle:Category:create }
project_back_category_edit:
    pattern:  /category/edit/{id}
    defaults: { _controller: ProjectBackBundle:Category:edit, id: '1' }

project_back_background_list:
    pattern:  /background/list/
    defaults: { _controller: ProjectBackBundle:Background:list }
project_back_background_rank:
    pattern:  /background/rank
    defaults: { _controller: ProjectBackBundle:Background:rank }
project_back_background_rank_post:
    pattern:  /background/rank/post
    defaults: { _controller: ProjectBackBundle:Background:rankPost }
project_back_background_create:
    pattern:  /background/create
    defaults: { _controller: ProjectBackBundle:Background:create }
project_back_background_edit:
    pattern:  /background/edit/{id}
    defaults: { _controller: ProjectBackBundle:Background:edit, id: '1' }

project_back_theme_list:
    pattern:  /theme/list/
    defaults: { _controller: ProjectBackBundle:Theme:list }
project_back_theme_create:
    pattern:  /theme/create
    defaults: { _controller: ProjectBackBundle:Theme:create }
project_back_theme_edit:
    pattern:  /theme/edit/{id}
    defaults: { _controller: ProjectBackBundle:Theme:edit, id: '1' }

project_back_reservation_list:
    pattern:  /reservation/list/
    defaults: { _controller: ProjectBackBundle:Reservation:list }

project_back_menu_list:
    pattern:  /menu/list/
    defaults: { _controller: ProjectBackBundle:Menu:list }
project_back_menu_create:
    pattern:  /menu/create
    defaults: { _controller: ProjectBackBundle:Menu:create }
project_back_menu_edit:
    pattern:  /menu/edit/{id}
    defaults: { _controller: ProjectBackBundle:Menu:edit, id: '1' }

project_back_menu_item_list:
    pattern:  /menu/{menu}/item/list/
    defaults: { _controller: ProjectBackBundle:MenuItem:list }
    options:
        expose: true
project_back_menu_item_create:
    pattern:  /menu/{menu}/item/create
    defaults: { _controller: ProjectBackBundle:MenuItem:create }
    options:
        expose: true
project_back_menu_item_edit:
    pattern:  /menu/{menu}/item/edit/{id}
    defaults: { _controller: ProjectBackBundle:MenuItem:edit, id: '1', menu:'1' }
    options:
        expose: true
project_back_menu_item_rank:
    pattern:  /menu/{menu}/item/rank
    defaults: { _controller: ProjectBackBundle:MenuItem:rank }
    options:
        expose: true
project_back_menu_item_rank_post:
    pattern:  /menu/{menu}/item/rank/post
    defaults: { _controller: ProjectBackBundle:MenuItem:rankPost }
    requirements:
      _method: POST
    options:
        expose: true

project_back_setting_list:
    pattern:  /setting/list/
    defaults: { _controller: ProjectBackBundle:Setting:list }
project_back_setting_create:
    pattern:  /setting/create
    defaults: { _controller: ProjectBackBundle:Setting:create }
project_back_setting_edit:
    pattern:  /setting/edit/{id}
    defaults: { _controller: ProjectBackBundle:Setting:edit, id: '1' }

project_back_setting_list:
    pattern:  /setting/list/
    defaults: { _controller: ProjectBackBundle:Setting:list }
project_back_setting_create:
    pattern:  /setting/create
    defaults: { _controller: ProjectBackBundle:Setting:create }
project_back_setting_edit:
    pattern:  /setting/edit/{id}
    defaults: { _controller: ProjectBackBundle:Setting:edit, id: '1' }

project_back_newsletter_list:
    pattern:  /newsletter/list/
    defaults: { _controller: ProjectBackBundle:Newsletter:list }
project_back_newsletter_create:
    pattern:  /newsletter/create
    defaults: { _controller: ProjectBackBundle:Newsletter:create }
project_back_newsletter_edit:
    pattern:  /newsletter/edit/{id}
    defaults: { _controller: ProjectBackBundle:Newsletter:edit, id: '1' }