project_front:
    resource: "@ProjectFrontBundle/Controller/DefaultController.php"
    prefix:   /
    type:     annotation

#project_front:
#    resource: "@ProjectFrontBundle/Resources/config/routing.yml"
#    prefix:   /

project_user:
    resource: "@ProjectUserBundle/Resources/config/routing.yml"
    prefix:   /

project_back:
    resource: "@ProjectBackBundle/Resources/config/routing.yml"
    prefix:   /dashboard/

_imagine:
    resource: .
    type:     imagine

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

project_front_modal_message:
    pattern:  /modal/mensage
    defaults: { _controller: ProjectFrontBundle:Modal:message }
project_front_modal_login:
    pattern:  /modal/login
    defaults: { _controller: ProjectFrontBundle:Modal:login }
project_front_modal_search:
    pattern:  /modal/busqueda
    defaults: { _controller: ProjectFrontBundle:Modal:search }
project_front_modal_newsletter:
    pattern:  /modal/newsletter
    defaults: { _controller: ProjectFrontBundle:Modal:newsletter }
project_front_modal_direction:
    pattern:  /modal/direccion
    defaults: { _controller: ProjectFrontBundle:Modal:direction }
project_front_practice:
    pattern:  /practica
    defaults: { _controller: ProjectFrontBundle:Practice:index }

project_front_ruta:
    pattern:  /rutarss
    defaults: { _controller: ProjectFrontBundle:Helpers:feednes }

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

admin:
    resource:   '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:     /admin

_sonata_admin:
    resource:   .
    type:       sonata_admin
    prefix:     /admin