parameters:
#    project_user.example.class: Project\UserBundle\Example

services:
#    project_user.example:
#        class: %project_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    project.registration.form.type:
        class: Project\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags: [{ name: "form.type", alias: "project_user_registration" }]

    project.invitation.form.type:
        class: Project\UserBundle\Form\Type\InvitationFormType
        arguments: [@project.invitation.form.data_transformer]
        tags: [{ name: "form.type", alias: "project_invitation_type" }]

    project.invitation.form.data_transformer:
        class: Project\UserBundle\Form\DataTransformer\InvitationToCodeTransformer
        arguments: [@doctrine.orm.entity_manager]

    project.profile.form.type:
        class: Project\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: project_user_profile }

    project_user.form.type.theme:
        class: Project\UserBundle\Form\Type\ThemeType
        tags:
            - { name: form.type, alias: theme }

    project_background.form.type.theme:
        class: Project\UserBundle\Form\Type\BackgroundType
        tags:
            - { name: form.type, alias: background }

    project_background.form.type.reservation:
        class: Project\UserBundle\Form\Type\ReservationType
        tags:
            - { name: form.type, alias: reservation }

    project_background.form.type.page:
        class: Project\UserBundle\Form\Type\PageType
        tags:
            - { name: form.type, alias: page }

    project_background.form.type.category:
        class: Project\UserBundle\Form\Type\CategoryType
        tags:
            - { name: form.type, alias: category }