<?php

namespace Project\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BackgroundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackgroundRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM ProjectUserBundle:Background p ORDER BY p.name ASC'
            )
            ->getResult();
    }

    public function getAllLength()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(u.id) FROM ProjectUserBundle:Background u'
            )
            ->getSingleScalarResult();
    }
}
