<?php

namespace Project\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SearchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchRepository extends EntityRepository
{
	public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM ProjectUserBundle:Search p ORDER BY p.name ASC'
            )
            ->getResult();
    }

    public function getAllLength()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(u.id) FROM ProjectUserBundle:Search u'
            )
            ->getSingleScalarResult();
    }

    public function getDistinctRankingAll()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u.name, COUNT( u.id ) as cantidad FROM ProjectUserBundle:Search u GROUP BY u.name ORDER BY cantidad DESC'
            )
            ->getResult();
    }
}
