project_front_homepage:
    pattern:  /
    defaults: { _controller: ProjectFrontBundle:Default:index }

project_front_page:
    pattern:  /{_locale}/{id}/{friendlyname}
    defaults: { _controller: ProjectFrontBundle:Default:page }
    requirements:
        _locale:  es|en
